pkg load image;
clc;
close all;
clear all;
Img=imread('p1.jpg');
subplot(2,3,1);
imshow(Img);
title('Original Image');
grayImg=rgb2gray(Img);
subplot(2,3,2);
imshow(grayImg);
title('RGB to GRAY');
hvImg=rgb2hsv(Img);
subplot(2,3,3);
imshow(hvImg);
title('RGB to HSV');
rg=hsv2rgb(hvImg);
hsgray=rgb2gray(rg);
subplot(2,3,4);
imshow(hsgray);
title('HSV to GRAY');
binary=im2bw(Img);
subplot(2,3,5);
imshow(binary);
title('RGB to BINARY');
cb=rgb2ycbcr(Img);
subplot(2,3,6);
imshow(cb);
title('RGB to YCBCR');
